// <auto-generated />
using System;
using KAEAGoalWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KAEAGoalWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241223031940_AddRefreshToken")]
    partial class AddRefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KAEAGoalWebAPI.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("A_USER_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("USERSA_USER_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("USERSA_USER_ID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.User", b =>
                {
                    b.Property<Guid>("A_USER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Branch")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletionStateCode")
                        .HasColumnType("int");

                    b.Property<int?>("IsAdmin")
                        .HasColumnType("int");

                    b.Property<int?>("IsBkk")
                        .HasColumnType("int");

                    b.Property<int?>("IsQSC")
                        .HasColumnType("int");

                    b.Property<bool>("Isshop")
                        .HasColumnType("bit");

                    b.Property<bool>("Issup")
                        .HasColumnType("bit");

                    b.Property<string>("LOGON_NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ST_Dept_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StateCode")
                        .HasColumnType("int");

                    b.Property<string>("USER_EMAIL")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("USER_PASSWORD")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("User_Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("User_Position")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("VersionNumber")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("A_USER_ID");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("KAEAGoalWebAPI.Models.User", "USERS")
                        .WithMany()
                        .HasForeignKey("USERSA_USER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("USERS");
                });
#pragma warning restore 612, 618
        }
    }
}
