// <auto-generated />
using System;
using KAEAGoalWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KAEAGoalWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250127034702_AddRewardAndUserReward")]
    partial class AddRewardAndUserReward
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KAEAGoalWebAPI.Models.CodeMission", b =>
                {
                    b.Property<Guid>("CodeMissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code_Mission_Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MISSION_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CodeMissionID");

                    b.HasIndex("MISSION_ID")
                        .IsUnique();

                    b.ToTable("CODE_MISSIONS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.CoinTransaction", b =>
                {
                    b.Property<Guid>("COIN_TRANSACTION_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("A_USER_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("Coin_Type")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Transaction_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Transaction_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("COIN_TRANSACTION_ID");

                    b.ToTable("COIN_TRANSACTIONS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.Mission", b =>
                {
                    b.Property<Guid>("MISSION_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Accept_limit")
                        .HasColumnType("int");

                    b.Property<int>("Coin_Reward")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Current_Accept")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expire_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_Limited")
                        .HasColumnType("bit");

                    b.Property<string>("MISSION_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MISSION_TYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mission_Point")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("MISSION_ID");

                    b.ToTable("MISSIONS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.MissionImage", b =>
                {
                    b.Property<Guid>("IMAGE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MISSION_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Uploaded_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("IMAGE_ID");

                    b.HasIndex("MISSION_ID");

                    b.ToTable("MISSION_IMAGES");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.QrCodeMission", b =>
                {
                    b.Property<Guid>("QR_MISSION_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MISSION_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRCodeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QR_MISSION_ID");

                    b.HasIndex("MISSION_ID")
                        .IsUnique();

                    b.ToTable("QR_CODE_MISSIONS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("A_USER_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("A_USER_ID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.Reward", b =>
                {
                    b.Property<Guid>("REWARD_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PRICE")
                        .HasColumnType("int");

                    b.Property<int>("QUANTITY")
                        .HasColumnType("int");

                    b.Property<string>("REWARD_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("REWARD_ID");

                    b.ToTable("REWARDS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.RewardImage", b =>
                {
                    b.Property<Guid>("REWARD_IMAGE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("REWARD_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Uploaded_At")
                        .HasColumnType("datetime2");

                    b.HasKey("REWARD_IMAGE_ID");

                    b.HasIndex("REWARD_ID");

                    b.ToTable("REWARD_IMAGES");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.User", b =>
                {
                    b.Property<Guid>("A_USER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Branch")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletionStateCode")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsAdmin")
                        .HasColumnType("int");

                    b.Property<int?>("IsBkk")
                        .HasColumnType("int");

                    b.Property<int?>("IsQSC")
                        .HasColumnType("int");

                    b.Property<bool>("Isshop")
                        .HasColumnType("bit");

                    b.Property<bool>("Issup")
                        .HasColumnType("bit");

                    b.Property<string>("LOGON_NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ST_Dept_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StateCode")
                        .HasColumnType("int");

                    b.Property<string>("USER_EMAIL")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("USER_PASSWORD")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("User_Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("User_Position")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("VersionNumber")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("A_USER_ID");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.UserCodeMission", b =>
                {
                    b.Property<Guid>("USER_CODE_MISSION_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("A_USER_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MISSION_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Submit_At")
                        .HasColumnType("datetime2");

                    b.HasKey("USER_CODE_MISSION_ID");

                    b.HasIndex("A_USER_ID");

                    b.HasIndex("MISSION_ID");

                    b.ToTable("USER_CODE_MISSIONS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.UserMission", b =>
                {
                    b.Property<Guid>("USER_MISSION_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("A_USER_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Accepted_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Completed_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_Collect")
                        .HasColumnType("bit");

                    b.Property<Guid>("MISSION_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Verification_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("USER_MISSION_ID");

                    b.HasIndex("A_USER_ID");

                    b.HasIndex("MISSION_ID");

                    b.ToTable("USER_MISSIONS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.UserPhotoMission", b =>
                {
                    b.Property<Guid>("USER_PHOTO_MISSION_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("A_USER_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Approve")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Approve_By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MISSION_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("USER_MISSION_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Uploaded_At")
                        .HasColumnType("datetime2");

                    b.HasKey("USER_PHOTO_MISSION_ID");

                    b.HasIndex("A_USER_ID");

                    b.HasIndex("MISSION_ID");

                    b.HasIndex("USER_MISSION_ID");

                    b.ToTable("USER_PHOTO_MISSIONS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.UserPhotoMissionImage", b =>
                {
                    b.Property<Guid>("USER_PHOTO_MISSION_IMAGE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("USER_PHOTO_MISSION_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("USER_PHOTO_MISSION_IMAGE_ID");

                    b.HasIndex("USER_PHOTO_MISSION_ID");

                    b.ToTable("USER_PHOTO_MISSION_IMAGES");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.UserQRCodeMission", b =>
                {
                    b.Property<Guid>("USER_QRCODE_MISSION_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("A_USER_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Approve")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Approved_By")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MISSION_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Scanned_At")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("USER_MISSION_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("USER_QRCODE_MISSION_ID");

                    b.HasIndex("A_USER_ID");

                    b.HasIndex("MISSION_ID");

                    b.HasIndex("USER_MISSION_ID");

                    b.ToTable("USER_QR_CODE_MISSIONS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.UserReward", b =>
                {
                    b.Property<Guid>("USER_REWARD_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("A_USER_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("COLLECT_AT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("REDEEMED_AT")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("REWARD_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("USER_REWARD_ID");

                    b.HasIndex("A_USER_ID");

                    b.HasIndex("REWARD_ID");

                    b.ToTable("USER_REWARDS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.CodeMission", b =>
                {
                    b.HasOne("KAEAGoalWebAPI.Models.Mission", "Mission")
                        .WithOne("CodeMission")
                        .HasForeignKey("KAEAGoalWebAPI.Models.CodeMission", "MISSION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.MissionImage", b =>
                {
                    b.HasOne("KAEAGoalWebAPI.Models.Mission", "Mission")
                        .WithMany("MISSION_IMAGES")
                        .HasForeignKey("MISSION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.QrCodeMission", b =>
                {
                    b.HasOne("KAEAGoalWebAPI.Models.Mission", "Mission")
                        .WithOne("QrCodeMission")
                        .HasForeignKey("KAEAGoalWebAPI.Models.QrCodeMission", "MISSION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("KAEAGoalWebAPI.Models.User", "USERS")
                        .WithMany()
                        .HasForeignKey("A_USER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("USERS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.RewardImage", b =>
                {
                    b.HasOne("KAEAGoalWebAPI.Models.Reward", "Reward")
                        .WithMany("REWARD_IMAGES")
                        .HasForeignKey("REWARD_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.UserCodeMission", b =>
                {
                    b.HasOne("KAEAGoalWebAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("A_USER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAEAGoalWebAPI.Models.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MISSION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.UserMission", b =>
                {
                    b.HasOne("KAEAGoalWebAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("A_USER_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KAEAGoalWebAPI.Models.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MISSION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.UserPhotoMission", b =>
                {
                    b.HasOne("KAEAGoalWebAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("A_USER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAEAGoalWebAPI.Models.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MISSION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAEAGoalWebAPI.Models.UserMission", "UserMission")
                        .WithMany()
                        .HasForeignKey("USER_MISSION_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("User");

                    b.Navigation("UserMission");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.UserPhotoMissionImage", b =>
                {
                    b.HasOne("KAEAGoalWebAPI.Models.UserPhotoMission", "UserPhotoMission")
                        .WithMany("IMAGES")
                        .HasForeignKey("USER_PHOTO_MISSION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPhotoMission");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.UserQRCodeMission", b =>
                {
                    b.HasOne("KAEAGoalWebAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("A_USER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAEAGoalWebAPI.Models.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MISSION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAEAGoalWebAPI.Models.UserMission", "UserMission")
                        .WithMany()
                        .HasForeignKey("USER_MISSION_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("User");

                    b.Navigation("UserMission");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.UserReward", b =>
                {
                    b.HasOne("KAEAGoalWebAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("A_USER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KAEAGoalWebAPI.Models.Reward", "Reward")
                        .WithMany()
                        .HasForeignKey("REWARD_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reward");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.Mission", b =>
                {
                    b.Navigation("CodeMission");

                    b.Navigation("MISSION_IMAGES");

                    b.Navigation("QrCodeMission");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.Reward", b =>
                {
                    b.Navigation("REWARD_IMAGES");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.UserPhotoMission", b =>
                {
                    b.Navigation("IMAGES");
                });
#pragma warning restore 612, 618
        }
    }
}
