// <auto-generated />
using System;
using KAEAGoalWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KAEAGoalWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250102071549_AddIsLitmitedMission")]
    partial class AddIsLitmitedMission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KAEAGoalWebAPI.Models.CodeMission", b =>
                {
                    b.Property<Guid>("CodeMissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code_Mission_Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MISSION_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CodeMissionID");

                    b.HasIndex("MISSION_ID")
                        .IsUnique();

                    b.ToTable("CODE_MISSIONS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.CoinTransaction", b =>
                {
                    b.Property<Guid>("COIN_TRANSACTION_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("A_USER_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("Coin_Type")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Transaction_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Transaction_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("COIN_TRANSACTION_ID");

                    b.ToTable("COIN_TRANSACTIONS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.Mission", b =>
                {
                    b.Property<Guid>("MISSION_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Coin_Reward")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expire_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_Limited")
                        .HasColumnType("bit");

                    b.Property<string>("MISSION_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MISSION_TYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mission_Point")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("MISSION_ID");

                    b.ToTable("MISSIONS", (string)null);
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.MissionImage", b =>
                {
                    b.Property<Guid>("IMAGE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MISSION_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Uploaded_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("IMAGE_ID");

                    b.HasIndex("MISSION_ID");

                    b.ToTable("MISSION_IMAGES", (string)null);
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("A_USER_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("A_USER_ID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.User", b =>
                {
                    b.Property<Guid>("A_USER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Branch")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletionStateCode")
                        .HasColumnType("int");

                    b.Property<int?>("IsAdmin")
                        .HasColumnType("int");

                    b.Property<int?>("IsBkk")
                        .HasColumnType("int");

                    b.Property<int?>("IsQSC")
                        .HasColumnType("int");

                    b.Property<bool>("Isshop")
                        .HasColumnType("bit");

                    b.Property<bool>("Issup")
                        .HasColumnType("bit");

                    b.Property<string>("LOGON_NAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ST_Dept_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StateCode")
                        .HasColumnType("int");

                    b.Property<string>("USER_EMAIL")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("USER_PASSWORD")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("User_Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("User_Position")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("VersionNumber")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("A_USER_ID");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.CodeMission", b =>
                {
                    b.HasOne("KAEAGoalWebAPI.Models.Mission", "Mission")
                        .WithOne("CodeMission")
                        .HasForeignKey("KAEAGoalWebAPI.Models.CodeMission", "MISSION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.MissionImage", b =>
                {
                    b.HasOne("KAEAGoalWebAPI.Models.Mission", "Mission")
                        .WithMany("MISSION_IMAGES")
                        .HasForeignKey("MISSION_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("KAEAGoalWebAPI.Models.User", "USERS")
                        .WithMany()
                        .HasForeignKey("A_USER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("USERS");
                });

            modelBuilder.Entity("KAEAGoalWebAPI.Models.Mission", b =>
                {
                    b.Navigation("CodeMission");

                    b.Navigation("MISSION_IMAGES");
                });
#pragma warning restore 612, 618
        }
    }
}
